version: '3'

services:
  reverse-proxy:
    image: traefik:3.0
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true) http://localhost:8080/dashboard#/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.seancheng.space`)" # curl -H Host:whoami.seancheng.space http://127.0.0.1
      - "traefik.http.routers.whoami.entrypoints=websecure" # Use the websecure entrypoint
